bot:
  # Токен бота, можно получить у @BotFather
  token: "8186829020:AAHOFrIgn5Ed532QGC-ZRKtNE1gIVq_MnJQ"

db:
  # Строка подключения к базе данных.
  # Ниже заполненный пример, если используете Docker Compose файл из каталога
  dsn: "postgresql+psycopg://superuser:superpassword@127.0.0.1:5433/postgres"
  # Если указать "yes", то при создании движка параметр "echo" будет True,
  # что приведёт к выводу на экран расширенной информации о взаимодействии
  # SQLAlchemy и базы данных. В противном случае укажите "no"
  is_echo: "yes"